# Generated by Django 3.1 on 2020-08-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listings_owner'),
    ]

