# Generated by Django 3.1 on 2020-08-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200810_1310'),
    ]


