# Generated by Django 3.1 on 2020-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
