# Generated by Django 3.1 on 2020-08-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
