# Generated by Django 3.1 on 2020-08-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listings_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
