# Generated by Django 3.1 on 2020-08-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='auctions.listings'),
        ),
    ]
