# Generated by Django 3.1 on 2020-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200810_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='listing_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
