# Generated by Django 3.1 on 2020-08-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200810_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='total',
        ),
    ]
