# Generated by Django 3.1 on 2020-08-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200810_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
