# Generated by Django 3.1 on 2020-08-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200810_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='listing_category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Education', 'Education'), ('Digital', 'Digital')], max_length=200),
        ),
    ]
