# Generated by Django 3.1 on 2020-08-12 17:19

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20200812_1634'),
    ]

   