# Generated by Django 3.1 on 2020-08-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20200812_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnername', models.CharField(max_length=200)),
                ('winnerreference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
            ],
        ),
    ]
