# Generated by Django 3.1 on 2020-08-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_winnerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winnerlist',
            name='winnerreference',
        ),
    ]
